version: '3.8'
services:
  app:
    build: .
    tty: true
    volumes:
      - ./python-argparse-generator:/usr/python-argparse-generator
      - ./README.md:/usr/python-argparse-generator/README.md
      - /usr/python-argparse-generator/node_modules